apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
  endpoints:
    - port: api
      path: "/actuator/prometheus"
      scheme: http
      interval: 15s
      honorLabels: true