apiVersion: v1
kind: ConfigMap
metadata:
  name: order-cm
  
data:
  username: 'otus-project'
  url: 'jdbc:postgresql://order-postgresql.default.svc.cluster.local:5432/postgres?prepareThreshold=0'
  applicationName: 'order'
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: olegmeditskiy96/otus-final-order:1.0
          ports:
            - containerPort: 8000
          env:
            - name: MANAGEMENT_SERVER_PORT
              value: '8000'
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: order-cm
                  key: username
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: order-cm
                  key: url
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: order-cm
                  key: applicationName
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: otus-homework-secret
                  key: password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-cm
                  key: kafka-host
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: config