apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-cm
data:
  username: 'otus-hw-8'
  url: 'jdbc:postgresql://inventory-postgresql.default.svc.cluster.local:5432/postgres?prepareThreshold=0'
  applicationName: 'inventory'
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    app: inventory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: olegmeditskiy96/hw-8-inventory-service:1.0
          ports:
            - containerPort: 8000
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: inventory-cm
                  key: username
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: inventory-cm
                  key: url
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: inventory-cm
                  key: applicationName
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: otus-homework-secret
                  key: password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-cm
                  key: kafka-host
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: config