apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-cm
data:
  username: 'otus-hw-7'
  url: 'jdbc:postgresql://auth-postgresql:5432/postgres?prepareThreshold=0'
  applicationName: 'auth'
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: olegmeditskiy96/hw-7-auth-service:1.0
          ports:
            - containerPort: 8000
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: auth-cm
                  key: username
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-cm
                  key: url
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: auth-cm
                  key: applicationName
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: otus-homework-secret
                  key: password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-cm
                  key: kafka-host
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: config